config_name: TEM image processing 

video_magnification: 0.0314

directory: {input_dir: ../input/exp_data/,
            video_name: 1423452,
            video_suffix: background,
            out_dir: output/exp_data/,
            w_contour_suffix: w_contour,
            w_d_min_suffix: w_d_min,
            w_base_border_suffix: w_base_border, 
            template_matching_suffix: template_matching
            }

process_frame: {gray_thresh: 230, smooth_deg: 5,noise_tol: 7}
template_matching: 
  method: cv.TM_CCOEFF
  template_crop: {left_width_crop_lb: 100,
                  left_width_crop_ub: 175,
                  left_height_crop_lb: 100,
                  left_height_crop_ub: 450, 
                  right_width_crop_lb: 250, 
                  right_width_crop_ub: 350,
                  right_height_crop_lb: 50, 
                  right_height_crop_ub: 450
                  }

base_border_detect:
  shifting_params_suffix: shifting_params 
  shift_xy_suffix: shift_xy
  w_base_border_suffix: w_base_border
  smoothing_factor: 0.5
  left_knot_idx: 9
  right_knot_idx: 6
  tolerance_width: 15


  
